server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  # instance:
  #   hostname: localhost

spring:
  application:
    name: gateway-api

jwt:
  public:
    key: classpath:app.pub
