server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  # instance:
  #   hostname: localhost

spring:
  application:
    name: gateway-api
  cloud:
      gateway:
          routes:
              - id: auth-service
                uri: lb://auth-service
                predicates:
                  - Path=/auth/**
                filters:
                - name: fallback
                  args:
                    name: auth
                    fallbackUri: http://localhost:8080/fallback/auth
              - id: user-service
                uri: lb://user-service
                predicates:
                  - Path=/user/**
                filters:
                - name: fallback
                  args:
                    name: user
                    fallbackUri: http://localhost:8080/fallback/user
              - id: account-service
                uri: lb://ACCOUNT-SERVICE
                predicates:
                  - Path=/account/**
                filters:
                - name: fallback
                  args:
                    name: account
                    fallbackUri: http://localhost:8080/fallback/account
              - id: payment-service
                uri: lb://PAYMENT-SERVICE
                predicates:
                  - Path=/payment/**
                filters:
                - name: fallback
                  args:
                    name: payment
                    fallbackUri: http://localhost:8080/fallback/payment


jwt:
  public:
    key: classpath:app.pub
